const Items = [
    {
        brand:"sony",
        model:"vaio",
        price:"34000",
        img:"./images/vaio.png"
    },
    {
        brand:"samsung",
        model:"champ",
        price:"40000",
        img:"./images/samsung-lap.png"
    },
    {
        brand:"dell",
        model:"vostro",
        price:"50000",
        img:"./images/dell.png"
    },
    {
        brand:"lenovo",
        model:"thinkpad",
        price:"32000",
        img:"./images/thinkpad.png"
    },
    {
        brand:"acer",
        model:"p245",
        price:"45000",
        img:"./images/acer.png"
    },
    {
        brand:"lenovo",
        model:"ideapad",
        price:"50000",
        img:"./images/ideapad.png"
    }
]

export default Items;